name: Continuous Deploy #action名称
on: [push] #在推送的时候运行此action

jobs:
  deploy_job: # 工作名称
    runs-on: ubuntu-latest  #运行环境
    name: build
    steps: # 步骤
      # check out the repository
      - name: Checkout    
        uses: actions/checkout@v3    #这里使用了github官方提供的action,checkout项目到虚拟机上

      - name: Install Dependencies
        run: yarn #执行的命令
      - name: Build
        run: yarn build

      # 利用action把build好的文件上传到服务器/workspace/react-note路径下,需要确认此目录已在服务端创建
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
            SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
            ARGS: '-avz --delete'
            SOURCE: 'dist/'
            REMOTE_HOST: ${{ env.HOST }}
            REMOTE_USER: ${{ env.USERNAME }}
            TARGET: /root/e # 服务器目标路径
